Release data 09/02/2022
HumanCellAtlas/schema-test-data pull request #16
Opened 2022-02-09 15:37 UTC by Wkt8

This is the test data for new imaging datasets. Additional imaging subgraphs have been added.
Specimen --> imaged_specimen --> sequence_file
specimen --> imaged_specimen --> image_file
specimen --> imaged_specimen --> analysis_file

Several entities were deleted in order to allow for our new validation in ingest (ingest-graph-validator).

Issues addressed:
https://github.com/HumanCellAtlas/metadata-schema/issues/1430

2022-02-15 17:47 UTC, hannes-ucsc requested changes, later dismissed
Something is off here. I see that two subgraphs were removed, and three added. I assume that the intent was to update two and add one.

2022-02-16 13:52 UTC, Wkt8 commented
Hi Hannes, my apologies. You should now see that 2 subgraphs remained the same, and 3 were added. This is because there are 3 subgraphs to do with imaging data and imaged_specimen. 
Specimen --> imaged_specimen --> sequence_file
specimen --> imaged_specimen --> image_file
specimen --> imaged_specimen --> analysis_file

2022-02-16 17:47 UTC, kbergin approved these changes

2022-02-16 19:00 UTC, hannes-ucsc commented
@danielsotirhos will review this for me

cc: @theathorn

2022-02-21 13:59 UTC, ESapenaVentura requested changes
Added 2 comments, other than that LGTM

2022-02-21 13:59 UTC, ESapenaVentura commented on tests/metadata/donor_organism/5bc2bf2f-eb98-5510-a386-172cef38f2f2_2021-01-01T00:00:00.000000Z.json
> -            "ontology_label": "COVID-19",
Why are these ontologies being deleted from this entity?

2022-02-21 13:59 UTC, ESapenaVentura commented on tests/metadata/donor_organism/9173ee6a-f1b2-5762-9272-3433b5ef7530_2021-01-01T00:00:00.000000Z.json
> -            "ontology": "MONDO:0100096",
Ditto to above comment

2022-02-23 18:47 UTC, danielsotirhos approved these changes
Approved.

2022-02-24 13:56 UTC, aherbst-broad approved these changes

2022-02-24 17:29 UTC, ruchim approved these changes
To be totally honest -- I'm not the best person to review what the structure of good test data looks like (just my lack of detailed knowledge on what type of cases to look out for ). I'm happy to approve because it looks right from what I know!

2022-02-28 09:38 UTC, Wkt8 commented on tests/metadata/donor_organism/5bc2bf2f-eb98-5510-a386-172cef38f2f2_2021-01-01T00:00:00.000000Z.json
> -            "ontology_label": "COVID-19",
This is completely my bad. An error that occurred during troubleshooting some of the issues with ingesting this dataset.

2022-02-28 09:53 UTC, amnonkhen approved these changes

2022-02-28 12:58 UTC, Wkt8 commented
This PR now has most of the reviews that were requested. @NoopDog please comment if you have any issues with this example of imaging subgraphs!

2022-02-28 12:58 UTC, merged