Improve SOP
HumanCellAtlas/schema-test-data pull request #29
Opened 2022-10-14 11:00 UTC by idazucchi

I'm suggesting this changes to the SOP based on the process of generating test data for the treatment protocol and cell-to-cell suspension.

Let me know if you would like to add something else!

2022-10-14 11:15 UTC, Wkt8 approved these changes
LGTM!

2022-10-17 13:42 UTC, amnonkhen requested changes, later dismissed
please link related ticket.
Link format is: org/repo#num where num is the issue or pr number.

2022-10-17 13:47 UTC, ESapenaVentura approved these changes
LGTM

2022-10-24 08:47 UTC, MightyAx approved these changes

2022-10-24 09:24 UTC, Wkt8 commented on README.md
> +11. Ensure you update the excel spreadsheet located in the schema-test-data repo with the up-to-date modified spreadsheet for the next cycle of generating test data
```suggestion
11. Ensure you update the excel spreadsheet (Schema_Test_Data.xlsx) located in the schema-test-data repo with the up-to-date modified spreadsheet for the next cycle of generating test data 
```

2022-10-24 09:24 UTC, Wkt8 requested changes
Change to specify the excel document! LGTM otherwise.

2022-10-24 09:25 UTC, Wkt8 approved these changes

2022-11-07 09:44 UTC, amnonkhen commented on README.md
> +1. Download the excel spreadsheet located in this folder (schema_test_data.xlsx) and modify it to include the new metadata-schema changes.
```suggestion
1. Download the excel spreadsheet located in this folder ([Schema_Test_Data.xlsx](./Schema_Test_Data.xlsx)) and modify it to include the new metadata-schema changes.
```

2022-12-23 01:31 UTC, merged